---
title: "Application exercise"
subtitle: "01 - First dataviz"
output:
  xaringan::moon_reader:
    seal: false
    css: 
      - css/xaringan-themer.css
      - css/slides.css
    lib_dir: libs
    nature:
      ratio: "16:9"
      highlightLines: true
      highlightStyle: solarized-light
      countIncrementalSlides: false
---

```{r child = "../setup.Rmd"}
```

## AE 01 - First dataviz

You have two options for this exercise:

- Option 1: Life expectancy over time 

- Option 2: COVID-19 fatality numbers across the globe (more complicated plot; if you want to warm up first, start with Option 1!)

Pick one and complete it. Optionally, try the other one as well.

To get the starter materials, download the file ae01.zip from the Sakai website's Resources section to a location on your computer that you'll be able to find again!

---

**Getting Started**


- Log in to R using the Class Container following these [instructions](https://www.introds.org/computing.html)

- Click on "Upload" in the bottom right hand window, and select the zip file you just downloaded (no need to unzip, R will do that for you)

---


.your-turn[
**Option 1.**

- In the Files pane (bottom right corner), spot the file called `w1-ae01a-lifeexp.Rmd`. 

- Open it and click "Knit".

- Then...
  - Go back to the file and change your name on top (in the `yaml` -- we'll talk about what this means later) and knit again.
  
  - Change the country names to those you're interested in. Spelling and capitalization must match how the countries appear in the data, so take a peek at the Appendix to confirm spelling.
  
  - Knit again. Voila, your first data visualization!
]

---

.your-turn[
**Option 2.**

- In the Files pane (bottom right corner), spot the file called `w1-ae01b-covid.Rmd`.

- Open it. You may get a message in the top of the upper left hand pane that the package *coronavirus* has not been installed -- click there to install it first. Then click "Knit".

- Then...
  - Go back to the file and change your name on top (in the `yaml` -- we'll talk about what this means later) and knit again.
  
  - Change the country names to those you're interested in. Spelling and capitalization must match how the countries appear in the data, so take a peek at the Appendix to confirm spelling.
  
  - Knit again. Voila, your first data visualization!
]
