---
title: 'Lab #11: Bringing It All Together'

output:
  tufte::tufte_html:    
    css: "sta199-labs.css"
    tufte_variant: envisioned
    highlight: pygments
    toc: no
    toc_depth: 1
  html_document:
    toc: no
    toc_depth: '1'
    df_print: paged
link-citations: yes
editor_options:
  chunk_output_type: console
---

## Goals

- Practice translating scientific hypotheses into statistical terms

- Design statistical analysis plans to evaluate hypotheses



For each study presented, define the variables and parameters of interest. Specify appropriate null and alternative hypotheses and a strategy for hypothesis testing
(this may include one hypothesis test or a series of hypothesis tests, in which case you
should provide the null and alternative hypotheses for each test conducted). If your
hypothesis testing strategy involves a statistical model, be sure to identify the outcome
variable and any predictor variables included in the model. Each study is inspired by
research in top public health and medical journals, though details of each study may have been altered for the sake of simplicity and time.


## Dating Violence (*American Journal of Public Health*)

Researchers are interested in whether sexual minority youth are at different risk
of physical dating violence compared to their majority counterparts. They have
recruited 100 sexual minority youth and 75 sexual majority youth and have asked
all youth whether they have ever experienced physical dating violence (reported as
a binary variable with values yes or no). Of the study participants, 65% report their
biological sex as female, and 35% report as male. Researchers are not sure whether
the association between sexual minority status and physical dating violence is the
same for each biological sex or not.

## Adolescent suicide contagion (*American Sociological Review*)

Adolescents participating in a large, population-representative study were
asked (1) whether they had a friend who tried to commit suicide in the past year,
and (2) how many times they personally tried to commit suicide in the past year.
The response to question (1) was a binary variable (yes/no), and the response to
question (2) was a count, with most adolescents reporting 0 suicide attempts; other
report options were 1, 2, 3, 4+ (the last category combined all those reporting four
or more attempts due to the very small number of adolescents in these categories).
Researchers wish to know whether the presence of a friend who tried to commit
suicide was associated with the count of personal suicide attempts.

## Palliative Care and Catastrophic Costs in Malawi after Diagnosis of Advanced Cancer (*The Lancet Global Health*)

Researchers were interested in whether receipt of palliative care after diagnosis of advanced cancer might affect medical costs. Eligible patients had been diagnosed with advanced terminal cancer and had an expected lifespan of at least 3 months. The outcome was defined as total health care costs from diagnosis to six months after diagnosis. In addition to the binary indicator of whether palliative care was received by the patient, the researchers wanted to control for the patient's gender, marital status (married or not), poverty level (living in extreme poverty, living in poverty, not living in poverty), and residence (urban or rural).


## COVID-19 Vaccine Acceptance in the Arab World (*Global Health Research and Policy*)

Researchers in Syria and the US designed an internet-based survey using social media platforms. This survey targeted adults who were able to read and understand Arabic and had access to the internet, and the survey was administered to individuals from all 22 Arab league countries between December 26, 2020 and January 14, 2021. 

Vaccine acceptance was measured by asking survey respondents if they would be willing to get the COVID-19 vaccine if it were freely available. The researchers wanted to understand factors related to vaccine acceptance, if the vaccine were to become available free charge, in order to target interventions to increase immunization rates. The factors they wanted to evaluate include World Bank income level of the respondent's country (high income, upper middle income, lower middle income, or low income), gender (measured as binary), age, education (less than high school, high school, university, graduate school), place of residence (inside or outside home country), prior COVID-19 infection (yes or no), and family death due to COVID-19 (yes or no). Because many respondents were living in areas with active armed conflicts, researchers also wanted to know whether living in a conflict-ridden area affected the association between the factors of interest and vaccine acceptance.

## Traffic Noise (*Environmental Health Perspectives*)

Researchers wish to determine whether indoor noise from traffic at night (i.e., levels of
traffic noise in decibels from nearby roads measured in bedrooms) is associated with
systolic blood pressure (measured in mm Hg). When evaluating this association,
they want to be careful to control for potential effects of traffic-related air pollution (measured as ppm CO) on systolic blood pressure, given that traffic-related air
pollution and traffic noise may be closely related.









